sudo: required
services:
  - docker

script:
  - docker-compose build
  - docker-compose run test

#language: python
#python:
#  - "2.7"
#  - "3.3"
#  - "3.5"
#  - "3.6"
#  - "pypy"
#install:
#  - pip install -r requirements.txt
#  - pip install pytest
#env:
#  YTDL_DB_PATH: ":memory:"
#script: py.test --tb=native
